// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200824022240_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("webapi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNasc");

                    b.Property<string>("Nome");

                    b.Property<int>("ProfessorId");

                    b.Property<string>("SobreNome");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "01/01/2020",
                            Nome = "Rodolfo",
                            ProfessorId = 1,
                            SobreNome = "Santos"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "01/01/2020",
                            Nome = "Camila",
                            ProfessorId = 2,
                            SobreNome = "Teixeira"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "01/01/2020",
                            Nome = "Yuri",
                            ProfessorId = 3,
                            SobreNome = "Mizuno"
                        });
                });

            modelBuilder.Entity("webapi.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Materia");

                    b.Property<string>("Nome");

                    b.Property<string>("SobreNome");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Materia = "Front-End",
                            Nome = "Gabriel",
                            SobreNome = "de Moraes Domingues Conceição"
                        },
                        new
                        {
                            Id = 2,
                            Materia = "Fundamentos da MPB",
                            Nome = "Jorge",
                            SobreNome = "Benjor"
                        },
                        new
                        {
                            Id = 3,
                            Materia = "Guitarra",
                            Nome = "Jimmi",
                            SobreNome = "Hendrix"
                        });
                });

            modelBuilder.Entity("webapi.Models.Aluno", b =>
                {
                    b.HasOne("webapi.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
